#!/usr/bin/env python3

# sort - sort lines of text
#
# USAGE
#     sort [FILE...]

from sys import argv, stdin

if __name__ == '__main__':
    argc = len(argv)
    if argc == 1:
        lines = stdin.readlines()
    else:
        lines = []
        for name in argv[1:]:
            with open(name) as f:
                lines.extend(f.readlines())
    lines.sort()
    for line in lines:
        print(line, end='')
